# Generated by Django 5.0.6 on 2024-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(max_length=20)),
                ('stdclass', models.IntegerField()),
                ('stdsection', models.CharField(max_length=1)),
                ('joindate', models.DateField()),
            ],
        ),
    ]
